name: Test importlib_metadata from conda-forge in conda py37
on:
  pull_request:

jobs:
  run-test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.7"

      - name: Conda install importlib_metadata
        run: |
          conda info
          conda install -c conda-forge importlib_metadata --yes
          conda list

      - name: Report conda dependency tree
        run: |
          conda install conda-tree
          conda-tree deptree --full
