name: Test installing and running xx in conda
on:
  pull_request:

jobs:
  run-test:
    name: test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          channels: conda-forge

      - name: Conda set up and reporting
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Pip install sonpy
        run: |
          pip install sonpy

      - name: Test import sonpy
        run: |
          python -c "import sonpy; print(sonpy.__version__)"
