name: Test installing and running scanimage-tiff-reader on x86 macos on conda
on:
  pull_request:

jobs:
  run-test:
    name: test
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          channels: conda-forge

      - name: Conda set up and reporting
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Install scanimage-tiff-reader
        run: |
          pip install scanimage-tiff-reader
          python -c "import ScanImageTiffReader; from ScanImageTiffReader import ScanImageTiffReader as reader; print(ScanImageTiffReader.__version__)"

      # - name: Conda install zipp
      #   run: |
      #     conda install zipp
      #     conda list --show-channel-urls

      # - name: Test import zipp
      #   run: |
      #     python -c "import zipp; print(zipp.__version__)"
