name: Test tox from conda-forge in conda py37
on:
  pull_request:

jobs:
  run-test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.7"
          channels: conda-forge

      - name: Conda install tox
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info
          conda install tox

      - name: Conda reporting
        run: |
          conda info
          conda config --show-sources
          conda list --show-channel-urls

      - name: Report conda dependency tree
        run: |
          conda install conda-tree
          conda-tree deptree --full

      #- name: Pip install tox
      #  run: |
      #    pip install tox

      - name: Run tox
        run: |
          tox -e test
