name: Test pluggy and importlib_metadata>1.7 from conda-forge in conda py37
on:
  pull_request:

jobs:
  run-test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          # auto-update-conda: true
          # activate-environment: true
          python-version: "3.7"
          channels: conda-forge

      - name: Conda install pluggy
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda info
          conda install pluggy "importlib_metadata==4.11.4"
          conda list

      - name: Report conda dependency tree
        run: |
          conda install conda-tree
          conda-tree deptree --full
